app:
    resource: '@AppBundle/Controller/'
    schemes: https
    type: annotation

home:
    path: /
    defaults:
      _controller:   FrameworkBundle:Template:template
      template:     :static:index.html.twig
      maxAge:       0
      sharedAge:    0

about:
    path: /about
    defaults:
      _controller:   FrameworkBundle:Template:template
      template:     :static:about.html.twig
      maxAge:       0
      sharedAge:    0

logout:
    path: /logout