# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']


    ### Command Handlers ###

    tinfoil.command.create_admin:
        class: AppBundle\Messaging\Handler\AddAdminUserHandler
        public: true
        arguments: ['@doctrine.orm.default_entity_manager', '@security.user_password_encoder.generic']
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\AddAdminUser }

    tinfoil.command.forgot_password:
        class: AppBundle\Messaging\Handler\ForgotPasswordHandler
        public: true
        arguments:
            $em: '@doctrine.orm.default_entity_manager'
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\ForgotPassword }

    tinfoil.command.register_user:
        class: AppBundle\Messaging\Handler\RegisterUserHandler
        public: true
        arguments: ['@doctrine.orm.default_entity_manager', '@security.user_password_encoder.generic']
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\RegisterUser }

    tinfoil.command.confirm_account:
        class: AppBundle\Messaging\Handler\ConfirmAccountHandler
        public: true
        arguments:
            $em: '@doctrine.orm.default_entity_manager'
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\ConfirmAccount }

    tinfoil.command.reset_password:
        class: AppBundle\Messaging\Handler\ResetPasswordHandler
        public: true
        arguments:
            $em: '@doctrine.orm.default_entity_manager'
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\ResetPassword }

    tinfoil.command.increment_failed_login_attempts:
        class: AppBundle\Messaging\Handler\IncrementFailedLoginAttemptsHandler
        public: true
        arguments:
            $em: '@doctrine.orm.default_entity_manager'
            $maxFailedLoginAttempts: '%max_failed_login_attempts%'
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\IncrementFailedLoginAttempts }

    tinfoil.command.send_account_recovery_email:
        class: AppBundle\Messaging\Handler\SendAccountRecoveryEmailHandler
        public: true
        arguments:
            $em: '@doctrine.orm.default_entity_manager'
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\SendAccountRecoveryEmail }

    tinfoil.command.recover_disabled_account:
        class: AppBundle\Messaging\Handler\RecoverDisabledAccountHandler
        public: true
        arguments:
            $em: '@doctrine.orm.default_entity_manager'
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\RecoverDisabledAccount }

    tinfoil.command.register_chub:
        class: AppBundle\Messaging\Handler\RegisterChubHandler
        public: true
        arguments:
            $em: '@doctrine.orm.default_entity_manager'
            $chubEm: '@doctrine.orm.chub_entity_manager'
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\RegisterChub }

    tinfoil.command.fill_order:
        class: AppBundle\Messaging\Handler\FillOrderHandler
        public: true
        arguments:
            $em: '@doctrine.orm.default_entity_manager'
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\FillOrder }

    tinfoil.command.create_payment:
        class: AppBundle\Messaging\Handler\CreatePaymentHandler
        public: true
        arguments:
            $apiKey: '%mollie_api_key%'
            $em: '@doctrine.orm.default_entity_manager'
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\CreatePayment }

    tinfoil.command.send_order_email:
        class: AppBundle\Messaging\Handler\SendOrderEmailHandler
        public: true
        tags:
            - { name: command_handler, handles: AppBundle\Messaging\Command\SendOrderEmail }


    ### Services ###

    tinfoil.service.cart:
        class: AppBundle\Services\ShoppingCart\ShoppingCartService
        public: true
        arguments: ['@service_container', '@security.token_storage']

    tinfoil.service.session_cart:
        class: AppBundle\Services\ShoppingCart\SessionShoppingCart
        public: true
        arguments: ['@session', '@doctrine.orm.entity_manager']

    tinfoil.service.db_cart:
        class: AppBundle\Services\ShoppingCart\DatabaseShoppingCart
        public: true
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']


    ### Twig Extensions ###

    tinfoil.twig.order:
        class: AppBundle\Twig\OrderTotal
        public: true
        tags:
          - twig.extension

    tinfoil.twig.referer:
        class: AppBundle\Twig\Referer
        public: true
        arguments: ['@request_stack']
        tags:
          - twig.extension

    tinfoil.voter.order:
        class: AppBundle\Security\OrderVoter
        public: true
        tags:
          - security.voter


    ### Event Listeners ###

    tinfoil.event.interactive_login:
        class: AppBundle\EventListener\InteractiveLoginListener
        arguments: ['%max_failed_login_attempts%', '@doctrine.orm.entity_manager']
        public: true
        tags:
          - { name: kernel.event_listener, event: security.interactive_login }
          - { name: kernel.event_listener, event: security.authentication.failure }